exclude_paths:
    - docs/**/*
    - tests/**/*
    - migrations/**/*
    - rbac/migrations/**/*
    
ratings:
    paths:
        - /**
        - console/**
        - queries/**
        - rbac/**
        
engines:
    phpmd:
        enabled: true
    phpcodesniffer:
        enabled: true
